// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_completed_all_snow_levels = "CgkIn82q6YsbEAIQDA"; // <GPGSID>
        public const string achievement_5_balls_purchased = "CgkIn82q6YsbEAIQDQ"; // <GPGSID>
        public const string achievement_100_diamonds = "CgkIn82q6YsbEAIQBQ"; // <GPGSID>
        public const string achievement_first_purchase = "CgkIn82q6YsbEAIQBw"; // <GPGSID>
        public const string leaderboard_blitexs_endless = "CgkIn82q6YsbEAIQAQ"; // <GPGSID>
        public const string achievement_10_000_diamonds = "CgkIn82q6YsbEAIQEw"; // <GPGSID>
        public const string achievement_first_level = "CgkIn82q6YsbEAIQAg"; // <GPGSID>
        public const string achievement_unlocked_snow_endless = "CgkIn82q6YsbEAIQCQ"; // <GPGSID>
        public const string leaderboard_succes__gameover_rate = "CgkIn82q6YsbEAIQEg"; // <GPGSID>
        public const string achievement_first_gameover = "CgkIn82q6YsbEAIQAw"; // <GPGSID>
        public const string achievement_unlocked_endless = "CgkIn82q6YsbEAIQCA"; // <GPGSID>
        public const string achievement_completed_10_normal_levels = "CgkIn82q6YsbEAIQDg"; // <GPGSID>
        public const string leaderboard_blitexs_diamonds = "CgkIn82q6YsbEAIQEA"; // <GPGSID>
        public const string achievement_completed_all_normal_levels = "CgkIn82q6YsbEAIQCg"; // <GPGSID>
        public const string achievement_completed_10_snow_levels = "CgkIn82q6YsbEAIQDw"; // <GPGSID>
        public const string leaderboard_blitexs_special_diamonds = "CgkIn82q6YsbEAIQEQ"; // <GPGSID>
        public const string achievement_1000_diamonds = "CgkIn82q6YsbEAIQBg"; // <GPGSID>

}

